spring.application.name=ApiSIP

# Properties for the DB

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

# Properties for JWT security
api.security.jwt.private.key=${PRIVATE_KEY}
api.security.jwt.user.generator=${USER_GENERATOR}
default.user = 2

# Configuration email server
spring.mail.host=${GMAIL}
spring.mail.port=${SPRING_EMAIL_PORT}
spring.mail.username=${SPRING_EMAIL_USERNAME}
spring.mail.password=${SPRING_EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Configuration for Storage
storage.location=C:/ApiSIP/Student_Doc/uploads
storage.certificate.pdf=C:/ApiSIP/Base_Doc/Cedula_registro.pdf
storage.save.certificate=C:/ApiSIP/Student_Doc/generates/

# Configuration for Manage page Spring
spring.data.web.pageable.serialization-mode=via-dto

# Configuration for Logs
logging.file.name=C:/ApiSIP/Logs/pruebaLogs.log

logging.level.root=WARN
logging.level.org.springframework=WARN
logging.level.org.apache.tomcat=WARN
logging.level.org.hibernate=WARN
logging.level.com.zaxxer.hikari=WARN

logging.level.com.upiicsa.ApiSIP=INFO

# Format for Logs
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} | %-5level | %msg%n

# 5. (Optional) Format for IDE console
logging.pattern.console=%d{HH:mm:ss} | %-5level | %msg%n