spring.application.name=ApiSIP

# Properties for the DB
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Properties for JWT security
api.security.jwt.private.key=${PRIVATE_KEY}
api.security.jwt.user.generator=${USER_GENERATOR}
default.user = 2

# Configuration email server
spring.mail.host=${GMAIL}
spring.mail.port=${SPRING_EMAIL_PORT}
spring.mail.username=${SPRING_EMAIL_USERNAME}
spring.mail.password=${SPRING_EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Configuration for Storage
storage.location=C:/ApiSIP/Student_Doc/uploads
storage.certificate.pdf=C:/ApiSIP/Base_Doc/Cedula_registro.pdf
storage.save.certificate=C:/ApiSIP/Student_Doc/generates/